### ISSUE TITLE
How to Restrict Calendar To Only Current Year 

### ISSUE THREAD

**Issue by Behseini** [zabuto/calendar#11]
Hi,
Thanks for all efforts you have done on this. Just wondering if it is possible to restrict the Calendar to Only Current Year? 

Thanks

**Comment by sandeepitgrids** [comment]
Hi i have restricted my calendar with 6 month in onload, when i click on one button it will increment by more 6 months dynamically.. please help me to achieve this.
here is my code..

$("#my-calendar").zabuto_calendar({
						data: data,
						show_days:true,
						show_previous: 5,
						show_next: false,
						today: true,
					});

please share your answer with sandeep.itgrids.hyd@gmail.com
thanks in advance.

**Comment by zabuto** [comment]
Old issue, closing.
