### ISSUE TITLE
Calendar cell refresh

### ISSUE THREAD

**Issue by Duncs1** [zabuto/calendar#12]
Hi,

I've created a function that fires off when I click on a date cell. The function will either add or remove an event for the selected date depending on whether an event already exists or not.

Is there a way to refresh the display to show this new state for each clicked cell?

Thanks
Duncs

**Comment by thespinningimage** [comment]
Hi Fro,

your customisations are excellent and you know javascript at a far more advanced level than I ever will! I just wondered if there is any way to cause a refresh of a date cell easily in the original Zabuto calendar?  

thanks

Darren

**Comment by fro** [comment]
Hi Darren,

Unfortunately, I don't think it's possible with the original Zabuto code. :-(

**Comment by fro** [comment]
Hi, some has asked my for my customized Zabuto version. Don't have time to fork the project and do things the right way. So, here's a fiddle: http://jsfiddle.net/n2gkm4d9/

**Comment by robccc** [comment]
Darren this is possible, kind of.
I did it by deleting the calendar and reloading it.
comment out this line in the original js
 $calendarElement.attr('id', "zabuto_calendar_" + Math.floor(Math.random() * 99999).toString(36));
This stops it overwriting your original id

then do something like this;
$("#my-calendar").empty();
reloadCal();

where reloadCal just contains your original js to load the cal. in the first place.

**Comment by combomatrix** [comment]
Thanks a lot @robccc, your solution worked perfectly!

I simply deleted the line `j.attr("id","zabuto_calendar_"+Math.floor(Math.random()*99999).toString(36));` from the minified js.
Then emptied my div tag with `$("#datePickerrr").empty();` and initialized the calendar again.

Thanks,
combomatrix

**Comment by dittops** [comment]
Thanks @robccc , you solution is awesome. This saved my day :)

**Comment by youmax210139** [comment]
There is another way to avoid modifying the minified js.
``
$calendar = $("#calendar").zabuto_calendar({your_config});
``
Access the cell by
``
var date = '2019-01-01';
$("#"+$calendar.attr('id')+"_"+date 
``
Here is the code snippet for selecting date programatically
```
$calendar = $("#calendar").zabuto_calendar({your_config});

function changeZabutoDate(date){
    var dates = date.split('-');
    $calendar.empty();  //remove current calendar
    $calendar.parent().append('<div id='calendar'></div>'); 
    $calendar = $("#calendar").zabuto_calendar({
           'year': dates[0],
           'month': dates[1]
       });  //
    $("#"+$calendar.attr('id')+"_"+date).addClass('active');
}
```
