### ISSUE TITLE
Event functionality (in and out!)

### ISSUE THREAD

**Issue by thespinningimage** [zabuto/calendar#18]
Hi,

really impressed with your calendar - it looks great and is easy to use.

I have a couple of questions though...

I pass data in a string using the data syntax and that works fine (it's read from a database). Now I intend having a context menu appear when you click on a date and this will allow you to set individual events. As I will need to populate these back to calendar (in a single instance) and then back to the database (for all events for a complete update) - I'd really appreciate if you can tell me how to:

```
 --  add a single event when there are already events in the calendar I don't wish to lose
 --  retrieve all the events from the calendar (so I can pass them back to the database) 
```

I don't expect you to write the code by the way - some pointers of how to get at this stuff would be great though

Many thanks

TSI

**Comment by zabuto** [comment]
See v2 for events. Thank you for your input!
