### ISSUE TITLE
Custom badge problem

### ISSUE THREAD

**Issue by badeamihai** [zabuto/calendar#19]
Hello, these days, as i was working with the calendar i had to modify a piece of code so that i could add a custom class to the selected date. I didn't want to commit the changes on the repo because it may not be something you wanted, or i misunderstood it.

The original code is here:

``` javascript
// drawEvents function
...
if (typeof(value.badge) !== 'undefined' && value.badge !== false) {
    var badgeClass = (value.badge === true) ? '' : ' badge-' + value.badge;
    var dayLabel = $dayElement.data('day');
    $dayElement.html('<span class="badge badge-event' + badgeClass + '">' + dayLabel + '</span>');
}
...
```

The code seems to be able to take a class as a parameter ( besides true / false ) but the default class is also preserved, and may come in conflict with the one i supplied. ( default is orange and i want blue )

So i think it should look like this:

``` javascript
// drawEvents function
...
if (typeof(value.badge) !== 'undefined' && value.badge !== false) {
    var badgeClass = (value.badge === true) ? 'badge-event' : value.badge;
    var dayLabel = $dayElement.data('day');
    $dayElement.html('<span class="badge ' + badgeClass + '">' + dayLabel + '</span>');
}
...
```

Here is a fiddle i used for testing:
http://jsfiddle.net/1470bg5q/6/

You can also check and force a prefix to the class ( like 'badge-') but i think it might be confusing. People will add a class and expect that the same name will be used. Also they wont know the prefix until they search for it.

Hope this helps.

**Comment by zabuto** [comment]
the .badge-event class contains styling that I want to be applied to all badges to maintain an overall design. This includes padding and font-size. 

Your own css can be used to override the appearance of the base event badge class, for example change orange to blue while still preserving the overall appearance. You can achieve this with a simple color override. And you don't have to worry about the spacing.
