### ISSUE TITLE
How to update calendar events manually？

### ISSUE THREAD

**Issue by sharp** [zabuto/calendar#21]
If the events changed in server, How to update the calendar ?

**Comment by CamaroMan** [comment]
im also interested in this.. i have to refresh every time something changes, kind of defeats the purpose -

**Comment by egcerqueira** [comment]
Hi!

Any solution about this?

Someone has a workaround for this?

**Comment by pathikvejani** [comment]
Is there any update on this issue?

**Comment by vraimentres** [comment]
```
var elem = 'jQuery('#my-calendar');
function loadCalendar(){
    elem.empty().zabuto_calendar({
        ....
    });
};

// when document ready or needs to refresh the calendar
loadCalendar();
```
