### ISSUE TITLE
Calendar do not show next months events,

### ISSUE THREAD

**Issue by voltan** [zabuto/calendar#35]
Hello, I setup calendar by config like this : 

```
<div id="item-calendar"></div>
<script type="text/javascript">
    //<!--
            $(document).ready(function () {
            var eventData = [{"date":"2016-1-22","title":"2016-1-22","classname":"grade-2","badge":false},{"date":"2016-1-21","title":"2016-1-21","classname":"grade-2","badge":false},{"date":"2016-1-20","title":"2016-1-20","classname":"grade-2","badge":false},{"date":"2016-1-19","title":"2016-1-19","classname":"grade-2","badge":false},{"date":"2016-1-18","title":"2016-1-18","classname":"grade-2","badge":false},{"date":"2016-1-17","title":"2016-1-17","classname":"grade-2","badge":false},{"date":"2016-1-16","title":"2016-1-16","classname":"grade-2","badge":false},{"date":"2016-1-15","title":"2016-1-15","classname":"grade-2","badge":false},{"date":"2016-1-14","title":"2016-1-14","classname":"grade-2","badge":false},{"date":"2016-1-05","title":"2016-1-05","classname":"grade-2","badge":false},{"date":"2016-1-04","title":"2016-1-04","classname":"grade-2","badge":false},{"date":"2016-1-03","title":"2016-1-03","classname":"grade-2","badge":false},{"date":"2016-1-02","title":"2016-1-02","classname":"grade-2","badge":false},{"date":"2016-1-01","title":"2016-1-01","classname":"grade-2","badge":false},{"date":"2015-12-31","title":"2015-12-31","classname":"grade-2","badge":false},{"date":"2015-12-30","title":"2015-12-30","classname":"grade-2","badge":false}];
            var legendData = [
                {type: "block", label: "Booked", classname: "grade-1"},
                {type: "block", label: "Non Available/Closed", classname: "grade-2"},
                {type: "block", label: "Today", classname: "grade-today"},
            ];
            $("#item-calendar").zabuto_calendar({
                cell_border: true,
                today: true,
                weekstartson: 0,
                language: "en",
                show_previous: false,
                show_next: 12,
                data: eventData,
                legend: legendData,
            });
        });
    //-->
</script>
```

This month days picked on calendar but next month days not show , see this images please : 

![snapshot41](https://cloud.githubusercontent.com/assets/562083/11863352/85086646-a4a8-11e5-9169-5dff88b5822d.png)
![snapshot42](https://cloud.githubusercontent.com/assets/562083/11863355/88186f3e-a4a8-11e5-89c2-bb0070a3a004.png)

can you please help us to fix this problem? thanks

**Comment by magicstickuk** [comment]
If I was a guessing man I would say that the AJAX is broke. So when you are pressing the navigation buttons to go to the next month the AJAX is not returning the events config. When you press the nav buttons to you get an error on the console log in firefox/chrome? That could help the developer/you diagnose your problem.

**Comment by dhonions** [comment]
I'm also having issues displaying events with fixed data like @voltan.  Looks like the script never makes it to parse fixed data.

**Comment by magicstickuk** [comment]
Really need to check what your console log is saying guys. No issues from me doing a similar setup as above (I'm using php to generate the event data Json)

**Comment by dhonions** [comment]
we're not using ajax to pull in the event data though. we are using the fixed data option, thus no ajax.get console error.

**Comment by magicstickuk** [comment]
Nothing to do with what you are doing. The calendar uses Ajax to load in data when you press the nav buttons. If there is an error in your set up the error with stop the Ajax from loading. Hense why I am suggesting you see if the console is firing any errors on the nav button press.

**Comment by voltan** [comment]
I fiend the problem finally , on JSON array , `2016-1-22` should be `2016-01-22` , or `2016-3-4` , should be `2016-03-04`

**Comment by guillembb** [comment]
Hi, same problem here, events are shown in the current month only. The dates are correct (with leading zeroes). The console says nothing so I don't know what info can be useful for you.
