### ISSUE TITLE
Azerbaijani language support

### ISSUE THREAD

**Issue by ab192130** [zabuto/calendar#4]
How to localize month names to my language?

**Comment by ab192130** [comment]
Can you add support for Azerbaijani? Thanks!

**Comment by zabuto** [comment]
Can you provide the translation? Please use this format for supplying the info:
month_labels: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
dow_labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

**Comment by limpapud** [comment]
Translated and pushed to main branch. Please check.

**Comment by zabuto** [comment]
Do you have a link to this main branch?

**Comment by limpapud** [comment]
My bad. Pulled, please check.

**Comment by zabuto** [comment]
Merged and tagged. Thanks :-)
