### ISSUE TITLE
current day badge not showing

### ISSUE THREAD

**Issue by rohantapiyawala** [zabuto/calendar#40]
current day badge is not shown if the day has an event ... need to fix that issue.

**Comment by mroffice** [comment]
Shows for me - quick check that you're not using the same colour background for `.badge-today` and your event class?

**Comment by lorengrayh** [comment]
I have this issue as well. The "badge-today" class is not added to a current day that has an event.

**Comment by juancmenj** [comment]
hello! I have to same problem! 
I need showing "today" in badge event!

**Comment by zabuto** [comment]
See v2. 
The today markup will still be replaced in case of an event. 
You can use the `.zabuto-calendar__day--today` css class added to the cell or add an extra class to the event data class or markup if the date is today.
