### ISSUE TITLE
Add Chinese language support.

### ISSUE THREAD

**Issue by CallMeXYZ** [zabuto/calendar#43]

**Comment by Snowfish1994** [comment]
//find the position of "$.fn.zabuto_calendar_language = function(a) {"
//and add these code in switch `case`

	case "cn":
		return {
			month_labels : [ "一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
			dow_labels : [ "星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日" ]
		};
		break;

**Comment by zabuto** [comment]
Language has been added
