### ISSUE TITLE
Dynamic events from MySQL Database

### ISSUE THREAD

**Issue by JoelGeek** [zabuto/calendar#44]
Hi, please how can i dynamically load events from a MySQL Database?

**Comment by martijn1k** [comment]
Create a PHP script that pulls MySQL data, then call it using the ajax function?
The tools are basically there, it's pretty straightforward.

**Comment by JoelGeek** [comment]
thanks for your response. Can you point me to any example?

**Comment by zabuto** [comment]
This repo only contains a simple jQuery plugin. Closing, not within scope.
