### ISSUE TITLE
duplicate id usage

### ISSUE THREAD

**Issue by bschelling** [zabuto/calendar#52]
the drawCalendar function adds a duplicate id in line 60:
`var $containerHtml = $('<div class="zabuto_calendar" id="' + $calendarElement.attr('id') + '"></div>');`

I'm not a zabuto calendar expert but this looks unnecessary and triggers an error in our testing tools.

**Comment by zabuto** [comment]
Id has been removed.
`var $containerHtml = $('<div class="zabuto_calendar"></div>');`
