### ISSUE TITLE
SK and HU language

### ISSUE THREAD

**Issue by robimolnar** [zabuto/calendar#57]
Hi, Here is **Slovak** translation:
________________________________________________________________________________________________________
        case 'sk':
            return {
                month_labels: ["Január", "Február", "Marec", "Apríl", "Máj", "Jún", "Júl", "August", "September", "Október", "November", "December"],
                dow_labels: ["Po", "Ut", "St", "Št", "Pi", "So", "Ne"]
            };
            break;
__________________________________________________________________________________________________________
And here is **Hungarian**:
        case 'hu':
            return {
                month_labels: ["Január", "Február", "Március", "Április", "Május", "Június", "Július", "Augusztus", "Szeptember", "Október", "November", "December"],
                dow_labels: ["Hé", "Ke", "Sze", "Cs", "Pé", "Szo", "Va"]
            };
            break;

**Comment by zabuto** [comment]
Languages have been added
