### ISSUE TITLE
How to listen clicks on prev or next month icon

### ISSUE THREAD

**Issue by yongmin1983** [zabuto/calendar#58]
Hi, I want to know if there is a way to listen event on lick of calendar-month-navigation please?
I can get alert on '.dow-clickable' but not Class: calendar-month-navigation or ID:zabuto_calendar_nav-prev
	$('#zabutoCalendar').on('click','.dow-clickable',function(){
		alert($(this).attr('id') +' '+ $(this).attr('data-time'));		
	});
	$('#zabutoCalendar').on('click','<div class="calendar-month-navigation"></div>',function(){
		alert(123);
	});

**Comment by zabuto** [comment]
You can use the action_nav setting. See https://jsfiddle.net/zabuto/fqzp7tf4/ for an example.

**Comment by zabuto** [comment]
See v2 with events.
```
$el.zabuto_calendar();
$el.on('calendar:navigate', function (e) { /* ... */ });
```
