### ISSUE TITLE
Multiple dates

### ISSUE THREAD

**Issue by Teddy95** [zabuto/calendar#6]
Until now, one can add only one date per day.
It would be really great if one could add multiple appointments and their time.

**Comment by livewire1407** [comment]
+1

**Comment by livewire1407** [comment]
since it doesn't look like this is actively updated, I updated my backend code that sets the json events array to combine the multiple events html in the body of 1 "event" and then display the body for each day when clicked. So I basically treated each day as the "event" and updated the body to have info for each thing going on that day. Works for now but would really be nice if the JS code was updated to treat each event separately but when a day is clicked, display all events that day and not just 1

**Comment by fro** [comment]
Hi guys,

Have you seen that?

http://jsfiddle.net/n2gkm4d9/
http://francois-pourrier.com/work/zabuto-X/calendar.html

Now with:

init calendar with local json + ajax data
call public methods (to add just one event at a time for example)
add event through a modal (not the modal included in zabuto calendar, I've removed it)
show a list of events of a day
...
It's only few hours of work, there's lot of features to add and things to do to make it stable but it's usable. ;-)

Look carefully to the code... there's much more than the fiddle show actually:

I think you should add a public method really easily to change the color of the cell.

**Comment by CamaroMan** [comment]
nice little proj - is there anyway to make the bars stretch across 2 days? im working on a little booking thing and some bookings (like rentals) are consecutive days.

not a biggy - i can always for loop inside the loop for 2+ days and add onto the array - jst thought it would be nice to have them joined ;)

**Comment by fro** [comment]
@CamaroMan I'm pretty sure it's not a big deal to adapt that calendar to handle such cases. Adding event duration in the event json is the first step. Tweak the js and the css a little bit and here you go.
I'm not comfortable with the idea of duplicating the event.

I've not enough time for the moment to update my version of zabuto calendar, please share your code if you succeed. ;-)

**Comment by CamaroMan** [comment]
will do! absolutely bogged down right now and heading overseas but ill see :p

**Comment by radhava** [comment]
@fro please may I have access to the php files I really like your version and I need to use it.. Awaiting your early response..

**Comment by pabparfer** [comment]
@fro what else, was there anyway to mark multiple days if the event's duration is more than one day? I don't have enought with mark the start day.

Thanks in advance :)
